server:
  port: 8761
spring:
  application:
    name: discovery-service

  boot:
    admin:
      client:
        url: http://44.205.10.1:8888/admin
        instance:
          service-base-url: http://44.205.10.1:8888/admin
      
         
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://44.205.10.1:8761/eureka